theme: jekyll-theme-architect
title: [Seminario de Investigación II]
description: [Curso de seminario II de la Maestrìa en Ciencias Marinas y Costeras de la Universidad de San Carlos de Guatemala. Cuya fnalidad es escribir (1) un manuscrito cientìfico en la modalidad de Artìculo, ensayo o revisión (2) Su informe final hasta resultados]
